--- Button component.
---
--- Returns a normalized button spec with auto-generated id.
--- Ids are stable when provided, allowing dynamic widget usage.

local color = require("hollow.color")

local M = {}

local counter = 0

--- Reset the auto-id counter. Called once per render pass so autogenerated
--- ids stay stable across frames (hover state set on frame N must match the
--- id regenerated on frame N+1).
function M.reset()
  counter = 0
end

---@param opts { id?: string, text: string, kind?: "default"|"primary"|"destructive", on_click?: fun(e: { id: string }) }
---@return HollowUiDialogButton
function M.button(opts)
  opts = opts or {}
  if type(opts.text) ~= "string" or opts.text == "" then
    error("dialog buttons require a 'text' string")
  end

  counter = counter + 1
  local id = opts.id or ("dialog:button:" .. counter)

  return {
    _button = true,
    id = id,
    text = opts.text,
    kind = opts.kind or "default",
    on_click = opts.on_click,
  }
end

---@param theme table
---@param btn HollowUiDialogButton
---@param selected boolean
---@param hovered boolean
---@return { fg: string, bg?: string, bold?: boolean, radius: integer }
function M.button_style(theme, btn, selected, hovered)
  local kind = btn.kind or "default"
  local result = { radius = theme.radius or 4 }

  if selected or hovered then
    result.bold = true
    if kind == "primary" then
      result.fg = theme.primary_fg
      result.bg = theme.primary_bg
    elseif kind == "destructive" then
      result.fg = theme.destructive_fg
      result.bg = theme.destructive_bg
    else
      result.fg = theme.selected_fg
      result.bg = color.brighten_hex_color(theme.selected_bg, 0.25, theme.panel_bg)
    end
  else
    if kind == "primary" then
      result.fg = theme.primary_bg
    elseif kind == "destructive" then
      result.fg = theme.destructive_bg
    else
      result.fg = theme.fg
    end
  end

  return result
end

return M
