local M = {}

function M.setup(hollow)
  hollow.keymap.set("<C-S-c>", "copy_selection")
  hollow.keymap.set("<C-S-v>", "paste_clipboard")
  hollow.keymap.set("<S-Insert>", "paste_clipboard")
  hollow.keymap.set("<C-\\>", "split_vertical")
  hollow.keymap.set("<C-S-\\>", "split_horizontal")
  hollow.keymap.set("<C-t>", "new_tab")
  hollow.keymap.set("<C-w>", "close_tab")
  hollow.keymap.set("<C-S-w>", "close_pane")
  hollow.keymap.set("<C-Tab>", "next_tab")
  hollow.keymap.set("<C-S-Tab>", "prev_tab")
  hollow.keymap.set("<C-A-n>", "new_workspace")
  hollow.keymap.set("<C-A-Right>", "next_workspace")
  hollow.keymap.set("<C-A-Left>", "prev_workspace")
  hollow.keymap.set("<C-S-Left>", "focus_pane_left")
  hollow.keymap.set("<C-S-Right>", "focus_pane_right")
  hollow.keymap.set("<C-S-Up>", "focus_pane_up")
  hollow.keymap.set("<C-S-Down>", "focus_pane_down")
  hollow.keymap.set("<C-A-S-Left>", "resize_pane_left")
  hollow.keymap.set("<C-A-S-Right>", "resize_pane_right")
  hollow.keymap.set("<C-A-Up>", "resize_pane_up")
  hollow.keymap.set("<C-A-Down>", "resize_pane_down")
  hollow.keymap.set("<A-S-PageUp>", "scrollback_page_up")
  hollow.keymap.set("<A-S-PageDown>", "scrollback_page_down")
  hollow.keymap.set("<C-S-Home>", "scrollback_top")
  hollow.keymap.set("<C-S-End>", "scrollback_bottom")
end

return M
